repos:
-   repo: https://github.com/ambv/black
    rev: 25.11.0
    hooks:
    - id: black
      language_version: python3.12
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    - id: flake8
-   repo: https://github.com/PyCQA/bandit
    rev: '1.9.1'
    hooks:
    -   id: bandit
        args: [--recursive, -x, tests, -c, .bandit]
        files: .py$
